# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# WebMatrix Color Palette https://www.color-hex.com/color-palette/6143
#5a0f35
#d17040
#b80025
#23598b
#2da14c
# Ravenclaw Color Palette https://www.color-hex.com/color-palette/814
#0e1a40
#222f5b
#5d5d5d
#946b2d
#000000

format = """
$username\
[@](bg:#222f5b)\
$hostname\
[ ](bg:#5a0f35 fg:#222f5b)\
$directory\
[ ](bg:#5a0f35 fg:#222f5b)\
[ ](fg:#5a0f35)\
$fill\
[ ](fg:#23598b)\
$git_branch\
$git_metrics\
$git_status\
[](fg:#2da14c bg:#23598b)\
[](fg:#0e1a40 bg:#2da14c)\
$cmd_duration\
[](fg:#d17040 bg:#0e1a40)\
$time
$shell\
[](fg:#b80025)\
$character\
"""
# [](#222f5b)\
# [](fg:#d17040)
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#222f5b"
style_root = "fg:red bg:#222f5b"
format = '[ $user]($style)'

[hostname]
style = "bg:#222f5b"
format = "[$ssh_symbol$hostname]($style)"
ssh_only = false

[directory]
style = "bg:#5a0f35"
format = "[$path]($style)"
truncation_length = 7
truncate_to_repo = false
repo_root_style = "fg:#d17040 bg:#5a0f35"
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"/Documents" = "/  "
"/Dokumente" = "/  "
"/Downloads" = "/"
"/Music" = "/"
"/Pictures" = "/"
"/workspace" = "/ 華 "
"/Workspace" = "/ 華 "
"/hft" = "/ 拾 "
"/private" = "/ 﫸 "
"/iteratec" = "/  "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[fill]
symbol = "-"
style = "bold green"

[git_branch]
symbol = ""
style = "bg:#23598b"
format = '[ $symbol $branch ]($style)'

[git_metrics]
disabled = false
only_nonzero_diffs = false
added_style = "bold fg:green bg:#23598b"
deleted_style = "bold fg:red bg:#23598b"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[git_status]
style = "bg:#23598b"
format = '[$all_status$ahead_behind ]($style)'

[cmd_duration]
style = "bg:#0e1a40"
min_time = 0
format = "[ $duration ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#d17040"
format = '[$time ]($style)'

[shell]
disabled = false
style = "bg:#b80025"
format = '[ $indicator]($style)'

# Programming language context

[c]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[docker_context]
disabled = true
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[elm]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[golang]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[haskell]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[java]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[julia]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[nodejs]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[nim]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'

[rust]
symbol = ""
style = "bg:#2da14c"
format = '[ $symbol ]($style)'
